### PR TITLE
Add functionality to GUIMain to pull the readme from a specified URL in the mod.

### PR DESCRIPTION
**Pull request by flpydsk**
allow readmes to be held in a git repo and read from ingame

### CODE REVIEW

**Comment by flpydsk** [comment]
I have things working the way I want. Had issues with async briefly where it would load the readme several times , but that is solved now so its merged back in to the netreadme branch.

**Comment by flpydsk** [comment]
Current:
- Loads Readme from URL defined in Mod.ReadmeURL
- Option in pulsar mod loader settings to auto pull the readme when you open the mod page
- stores in KV by mod name
To Do:
- save/cache readme and only update on mod version change/manual reload.

**Comment by flpydsk** [comment]
This can pull a readme from a file in a url or from a file inside a zip with the same name as the mod.Name using mod.ReadmeURL => "file://readme.md"
mod.ReadmeURL => "https://example.com/readme.md"

**Review by DragonFire47 — CHANGES_REQUESTED** [review]
Seems functional enough, although the new thread feels like it could be handled better.

Examining how readme pulls are made, we can add some extra safety. Right now, a new thread will be created every frame for as long as PMLConfig.AutoPullReadme is true and the readme text is false. I recommend creating a Boolean for whether a readme pull was requested and checking for that before creating a thread.

Additionally, if the button to load the readme is called, it'll display a label for 1 frame. The label will then disappear until the button is pushed again.

**Comment by flpydsk** [comment]
Given the discussion Ill make some changes 
- dict
- ill move the threading inside the running check, so it does not even start a thread.
- ill also add some bounding around the unzipping

**Comment by flpydsk** [comment]
limit max file sizes for zipmods and for readmes
Moved to single dict
Added options to the GUI per below
image

**Review by DragonFire47 — APPROVED** [review]
Looks fine.

**Pull request merged**
